// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteSupplier.Persistance;

#nullable disable

namespace RemoteSupplier.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231120203932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Arquisoft.Remote.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Vendor")
                        .HasColumnType("longtext");

                    b.HasKey("Id", "Supplier");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 250,
                            Category = "Grocery",
                            Image = "https://picsum.photos/640/480/?image=756",
                            Name = "Table",
                            Price = 1329.3870578110068,
                            Vendor = "Deckow, Herman and Kautzer"
                        },
                        new
                        {
                            Id = 21,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 108,
                            Category = "Kids",
                            Image = "https://picsum.photos/640/480/?image=667",
                            Name = "Keyboard",
                            Price = 4474.0698915317707,
                            Vendor = "Emard - Bashirian"
                        },
                        new
                        {
                            Id = 22,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 247,
                            Category = "Toys",
                            Image = "https://picsum.photos/640/480/?image=241",
                            Name = "Ball",
                            Price = 6202.3518814186727,
                            Vendor = "Schamberger - Wilkinson"
                        },
                        new
                        {
                            Id = 23,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 35,
                            Category = "Jewelery",
                            Image = "https://picsum.photos/640/480/?image=1021",
                            Name = "Table",
                            Price = 8292.7559199861607,
                            Vendor = "Breitenberg Inc"
                        },
                        new
                        {
                            Id = 24,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 220,
                            Category = "Games",
                            Image = "https://picsum.photos/640/480/?image=567",
                            Name = "Pizza",
                            Price = 7710.4242504487638,
                            Vendor = "Pollich - Nitzsche"
                        },
                        new
                        {
                            Id = 25,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 43,
                            Category = "Jewelery",
                            Image = "https://picsum.photos/640/480/?image=690",
                            Name = "Car",
                            Price = 2241.4726759366067,
                            Vendor = "Senger, Okuneva and Kovacek"
                        },
                        new
                        {
                            Id = 26,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 102,
                            Category = "Clothing",
                            Image = "https://picsum.photos/640/480/?image=114",
                            Name = "Computer",
                            Price = 9701.5925517412852,
                            Vendor = "Heathcote, Rolfson and O'Kon"
                        },
                        new
                        {
                            Id = 27,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 71,
                            Category = "Clothing",
                            Image = "https://picsum.photos/640/480/?image=462",
                            Name = "Pizza",
                            Price = 9374.2715246433563,
                            Vendor = "Gulgowski and Sons"
                        },
                        new
                        {
                            Id = 28,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 78,
                            Category = "Baby",
                            Image = "https://picsum.photos/640/480/?image=599",
                            Name = "Ball",
                            Price = 7459.1307043835141,
                            Vendor = "Bauch, Champlin and Gutkowski"
                        },
                        new
                        {
                            Id = 29,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 39,
                            Category = "Health",
                            Image = "https://picsum.photos/640/480/?image=830",
                            Name = "Chicken",
                            Price = 1722.4907978375336,
                            Vendor = "Quigley, McGlynn and Daniel"
                        },
                        new
                        {
                            Id = 30,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 182,
                            Category = "Grocery",
                            Image = "https://picsum.photos/640/480/?image=771",
                            Name = "Fish",
                            Price = 7026.8845280303731,
                            Vendor = "VonRueden, Kris and Wilkinson"
                        },
                        new
                        {
                            Id = 31,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 64,
                            Category = "Clothing",
                            Image = "https://picsum.photos/640/480/?image=482",
                            Name = "Pizza",
                            Price = 9150.4127529857124,
                            Vendor = "Hahn LLC"
                        },
                        new
                        {
                            Id = 32,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 156,
                            Category = "Shoes",
                            Image = "https://picsum.photos/640/480/?image=479",
                            Name = "Table",
                            Price = 2389.0524178144656,
                            Vendor = "Lesch LLC"
                        },
                        new
                        {
                            Id = 33,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 238,
                            Category = "Garden",
                            Image = "https://picsum.photos/640/480/?image=906",
                            Name = "Sausages",
                            Price = 2320.2686098002578,
                            Vendor = "Hermann LLC"
                        },
                        new
                        {
                            Id = 34,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 214,
                            Category = "Music",
                            Image = "https://picsum.photos/640/480/?image=510",
                            Name = "Chips",
                            Price = 2873.1303091936443,
                            Vendor = "Waters, MacGyver and Walker"
                        },
                        new
                        {
                            Id = 35,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 77,
                            Category = "Movies",
                            Image = "https://picsum.photos/640/480/?image=1040",
                            Name = "Bacon",
                            Price = 4228.4168828362399,
                            Vendor = "Deckow - VonRueden"
                        },
                        new
                        {
                            Id = 36,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 124,
                            Category = "Automotive",
                            Image = "https://picsum.photos/640/480/?image=881",
                            Name = "Tuna",
                            Price = 2906.3969344653251,
                            Vendor = "Schuster LLC"
                        },
                        new
                        {
                            Id = 37,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 123,
                            Category = "Computers",
                            Image = "https://picsum.photos/640/480/?image=267",
                            Name = "Ball",
                            Price = 8373.4185596160787,
                            Vendor = "Kling - Glover"
                        },
                        new
                        {
                            Id = 38,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 104,
                            Category = "Toys",
                            Image = "https://picsum.photos/640/480/?image=196",
                            Name = "Bike",
                            Price = 2482.012165525176,
                            Vendor = "Hayes and Sons"
                        },
                        new
                        {
                            Id = 39,
                            Supplier = "f9503a4d-d6ba-4a6e-b95c-068c71e5a6ea",
                            Amount = 122,
                            Category = "Toys",
                            Image = "https://picsum.photos/640/480/?image=78",
                            Name = "Chicken",
                            Price = 3949.2603427208605,
                            Vendor = "Hilpert and Sons"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
